### ISSUE TITLE
Adding HTML,CSS and Javascript cheat sheet

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [NirmalKumarJoshi/MyCode-DynamicEditor#4]
We can have a cheat sheet for the user which can help user to practice more easily.

**Comment by shreyansjain012** [comment]
I am interested in this issue @NirmalKumarJoshi can you explain it a bit more?

**Comment by NirmalKumarJoshi** [comment]
In the editor we can have a cheat sheet page or a downloadable document having HTML CSS and JS terms, function description, variables, staements etc. You can work on the issue and generate a pull request.  @shreyansjain012
